### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by ivankravets** [comment]
Please also update https://github.com/sle118/IrServiceBase/blob/dev/library.json

**Comment by sle118** [comment]
Done, thank you for the review!

**Comment by sle118** [comment]
@ivankravets  I'm trying to compile a project which has the following dependencies 
ESPITachEmulator->IrServiceBase 

I can't seem to get this to work

```

pio run --verbose
[Tue Feb 28 14:06:46 2017] Processing nodemcu (build_flags: -Wl,-Tesp8266.flash.4m.ld, lib_deps: https://github.com/sle118/ESPITachEmulator, platform: espressif8266, upload_speed: 921600, board: nodemcu, framework: arduino,
 lib_ldf_mode: deep+)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Library Storage: /home/sle118/workspace/platformio/ESP8266iTachEmulator/.piolibdeps
LibraryManager: Installing ESPITachEmulator
git version 2.5.0
Cloning into '/home/sle118/workspace/platformio/ESP8266iTachEmulator/.piolibdeps/installing-43FNhG-package'...
remote: Counting objects: 23, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 23 (delta 0), reused 20 (delta 0), pack-reused 0
Unpacking objects: 100% (23/23), done.
Checking connectivity... done.
ESPITachEmulator @ 219f209 has been successfully installed!
Collected 25 compatible libraries
Looking for dependencies...
Error: Could not find `IrServiceBase` dependency for `ESPITachEmulator` library
================================================================================================== [ERROR] Took 1.39 seconds ==================================================================================================
```

Oddly enough, I can install the IrServiceBase manually
```
pio lib install IrServiceBase
Library Storage: /home/sle118/workspace/platformio/ESP8266iTachEmulator/.piolibdeps
Looking for IrServiceBase library in registry
Found: http://platformio.org/lib/show/1515/IrServiceBase
LibraryManager: Installing id=1515
Downloading...
Unpacking...
IrServiceBase @ 1.0.0 has been successfully installed!
Installing dependencies
Looking for ProntoHex library in registry
Found: http://platformio.org/lib/show/1479/ProntoHex
LibraryManager: Installing id=1479
Downloading...
Unpacking...
ProntoHex @ 1.0 has been successfully installed!
Looking for ESPAsyncTCP library in registry
Found: http://platformio.org/lib/show/305/ESPAsyncTCP
LibraryManager: Installing id=305
Downloading...
Unpacking...
ESPAsyncTCP @ 1.0.0 has been successfully installed!
Looking for IRremoteESP8266 library in registry
Found: http://platformio.org/lib/show/1089/IRremoteESP8266
LibraryManager: Installing id=1089
Downloading...
Unpacking...
IRremoteESP8266 @ 1.0.0 has been successfully installed!
```


However, this doesn't seem to be pulling the latest manifest dependencies, to which I have added ESPAsyncWebServer.  The registry database (the library search page of platformio.org ( shows all the dependencies, though).

As I am trying to resolve dependencies issues with the libraries (they got developed together and I split them apart), this doesn't help!

thank you for any guidance you can provide!

**Comment by ivankravets** [comment]
I don't remember why, but PIO doesn't handle dependencies from VCS repositories.  Currently, dependencies are supported for the libraries from PIO Registry. See

```shell
pio lib -g install ESPITachEmulator
Library Storage: /Users/ikravets/.platformio/lib
Looking for ESPITachEmulator library in registry
Found: http://platformio.org/lib/show/1516/ESPITachEmulator
LibraryManager: Installing id=1516
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
ESPITachEmulator @ 1.0.0 has been successfully installed!
Installing dependencies
Looking for IrServiceBase library in registry
Found: http://platformio.org/lib/show/1515/IrServiceBase
LibraryManager: Installing id=1515 @ ^1.0.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
IrServiceBase @ 1.0.0 has been successfully installed!
Installing dependencies
Looking for ProntoHex library in registry
Found: http://platformio.org/lib/show/1479/ProntoHex
LibraryManager: Installing id=1479
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
ProntoHex @ 1.0 has been successfully installed!
Looking for ESPAsyncTCP library in registry
Found: http://platformio.org/lib/show/305/ESPAsyncTCP
LibraryManager: Installing id=305
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
ESPAsyncTCP @ 1.0.0 has been successfully installed!
Looking for IRremoteESP8266 library in registry
Found: http://platformio.org/lib/show/1089/IRremoteESP8266
LibraryManager: Installing id=1089
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
IRremoteESP8266 @ 1.0.0 has been successfully installed!
```

**Pull request merged**
